version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/python:3.6.2
      # 3.6.2-stretch-browsers # the primary container, where your job's commands are run

    steps:
      - checkout # check out the code in the project directory
      - run: pip install flask --user
      #- run: #FLASK_APP=h_w.py /home/circleci/.local/bin/flask run
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - run: 
          command:  |
            mkdir test_results
      - run:
          command: |
            pipenv run python testing.py test
      - store_test_results:
          path: test_results
  #deploy:
    #docker:
    
    #steps:
    #  - checkout
    # - run: echo 'export NKEY="my-project-74401-97deeaaa8507.json"' >> $BASH_ENV


#orbs:


workflows:
  version: 2
  install_and_initialize_cli: #workflow:
    jobs:
      - build
      #- deploy
